name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}
  IMAGE_TAG: latest
  WEBSITE_URL: http://ALB-web-212639990.ap-southeast-1.elb.amazonaws.com

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # ================= TELEGRAM START =================
      - name: Notify Deploy Started
        continue-on-error: true
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=🚀 DEPLOY STARTED%0AWorkflow Run: #${{ github.run_number }}%0ARepository: ${{ github.repository }}%0ABranch: ${{ github.ref_name }}%0ACommit: ${{ github.event.head_commit.message }}"

      # ================= CHECKOUT =================
      - name: Checkout source code
        uses: actions/checkout@v4

      # ================= NODE =================
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ================= INSTALL VALIDATORS =================
      - name: Install Validators
        run: |
          npm install -g htmlhint
          npm install -g stylelint stylelint-config-standard

      # ================= HTML CHECK =================
      - name: Validate HTML
        run: |
          htmlhint index.html

      # ================= CSS CHECK =================
      - name: Validate CSS
        run: |
          stylelint "**/*.css"

      # ================= JS CHECK =================
      - name: Validate JavaScript
        run: |
          node --check script.js

      # ================= AWS LOGIN =================
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # ================= LOGIN ECR =================
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ================= BUILD IMAGE =================
      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .

      # ================= LOCAL TEST =================
      - name: Run Test Container
        run: |
          docker run -d -p 8080:80 --name test-container $ECR_REPOSITORY:$IMAGE_TAG
          sleep 5

      # ================= LOCAL HEALTH CHECK =================
      - name: Test Container Local
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080)

          echo "Container status code: $STATUS"

          if [ "$STATUS" != "200" ]; then
            echo "Container test failed"
            exit 1
          fi

      # ================= CLEAN TEST CONTAINER =================
      - name: Remove Test Container
        if: always()
        run: |
          docker rm -f test-container || true

      # ================= TAG IMAGE =================
      - name: Tag Docker Image
        run: |
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      # ================= PUSH IMAGE =================
      - name: Push Docker Image to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      # ================= DEPLOY ECS =================
      - name: Deploy to ECS Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment

      # ================= WAIT ECS =================
      - name: Wait for ECS Stable
        run: |
          aws ecs wait services-stable \
            --cluster $ECS_CLUSTER \
            --services $ECS_SERVICE

      # ================= PRODUCTION CHECK =================
      - name: Check Production Website Health
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" $WEBSITE_URL)

          echo "Production status code: $STATUS"

          if [ "$STATUS" != "200" ]; then
            echo "Production website failed"
            exit 1
          fi

      # ================= TELEGRAM SUCCESS =================
      - name: Telegram Success Notification
        if: success()
        continue-on-error: true
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=✅ DEPLOY SUCCESS%0AWorkflow Run: #${{ github.run_number }}%0ACommit: ${{ github.event.head_commit.message }}%0ASHA: ${{ github.sha }}%0AService: ${{ env.ECS_SERVICE }}%0AStatus: Healthy"

      # ================= TELEGRAM FAILED =================
      - name: Telegram Failed Notification
        if: failure()
        continue-on-error: true
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=❌ DEPLOY FAILED%0AWorkflow Run: #${{ github.run_number }}%0ACommit: ${{ github.event.head_commit.message }}%0ABranch: ${{ github.ref_name }}%0AStopped before production deployment"
